# Generated by Django 6.0.4 on 2026-05-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('consent_launch', models.BooleanField(default=False)),
                ('consent_updates', models.BooleanField(default=False)),
                ('consent_reminders', models.BooleanField(default=False)),
                ('consent_tips', models.BooleanField(default=False)),
                ('how_heard', models.CharField(blank=True, max_length=200)),
                ('use_reasons', models.TextField(blank=True)),
                ('concerns', models.TextField(blank=True)),
                ('site_rating', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Waitlist Entries',
                'ordering': ['-joined_at'],
            },
        ),
    ]
